### ISSUE TITLE
Very Nice! graphiql-explorer?

### ISSUE THREAD

**Issue by idkjs** [zth/graphql-client-example-server#3]
How would we add https://github.com/OneGraph/graphiql-explorer to this package? I can't seem to figure it out. Thanks for sharing!

**Comment by zth** [comment]
Hmm, I'm not sure actually. Right now the server ships with Apollo's built in GraphiQL, but you're right, that doesn't use `graphiql-explorer` it seems. Maybe looking for how to integrate `graphiql-explorer` with `apollo-server` could point you in the right direction?
